import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nanum_Myeongjo } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const nanum = Nanum_Myeongjo({
  weight: ["400", "700"],
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nanum.className}>{children}</body>
    </html>
  );
}
